services:
  - type: web
    name: bidup
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: REDIS_URL
        sync: false
      - key: BASE_URL
        sync: false
      - key: USE_REDIS_MOCK
        value: false
